'use strict';
const express=require('express');
const Database=require('better-sqlite3');
const crypto=require('crypto');
const path=require('path');
const app=express();
const PORT=Number(process.env.PORT||3000);
const BASE_URL=(process.env.BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,'');
const SESSION_SECRET=process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex');
const BRAND_NAME=process.env.BRAND_NAME||'КЕЙСЕР';
const TELEGRAM_URL=process.env.TELEGRAM_URL||'https://t.me/';
const STEAM_API_KEY=process.env.STEAM_API_KEY||'';
app.use(express.json({limit:'128kb'}));
app.use(express.urlencoded({extended:false}));
app.get('/favicon.ico',(_,res)=>{res.type('svg').sendFile(path.join(__dirname,'favicon.svg'))});
app.use(express.static(__dirname,{index:'index.html'}));
const db=new Database(path.join(__dirname,'data.sqlite'));
db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,steamid TEXT UNIQUE NOT NULL,name TEXT NOT NULL,avatar TEXT NOT NULL DEFAULT '',balance_cents INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS live_drops(id INTEGER PRIMARY KEY AUTOINCREMENT,user_name TEXT NOT NULL,item_name TEXT NOT NULL,item_icon TEXT NOT NULL DEFAULT '',price_cents INTEGER,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS support_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,message TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);CREATE INDEX IF NOT EXISTS idx_drops_created ON live_drops(created_at DESC);`);
const clients=new Set();
const marketCache=new Map();
function clean(){db.prepare('DELETE FROM sessions WHERE expires_at<?').run(Date.now())};setInterval(clean,600000).unref();
function sign(v){return crypto.createHmac('sha256',SESSION_SECRET).update(v).digest('hex')}
function session(userId){const raw=`${crypto.randomBytes(24).toString('hex')}.${Date.now()}`;const token=`${raw}.${sign(raw)}`;db.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').run(token,userId,Date.now()+2592000000);return token}
function cookies(h=''){const o={};for(const p of h.split(';')){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return o}
function user(req){const t=cookies(req.headers.cookie||'').session;if(!t)return null;return db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?').get(t,Date.now())||null}
function setCookie(res,t){res.setHeader('Set-Cookie',`session=${encodeURIComponent(t)}; Path=/; HttpOnly; SameSite=Lax; Secure=${BASE_URL.startsWith('https://')}; Max-Age=2592000`)}
function clearCookie(res,t){if(t)db.prepare('DELETE FROM sessions WHERE id=?').run(t);res.setHeader('Set-Cookie','session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0')}
function broadcast(type,payload){const d=`event: ${type}\ndata: ${JSON.stringify(payload)}\n\n`;for(const r of clients){try{r.write(d)}catch{clients.delete(r)}}}
function steamLogin(){const p=new URLSearchParams({'openid.ns':'http://specs.openid.net/auth/2.0','openid.mode':'checkid_setup','openid.return_to':`${BASE_URL}/auth/steam/callback`,'openid.realm':BASE_URL,'openid.ns.sreg':'http://openid.net/extensions/sreg/1.1','openid.claimed_id':'http://specs.openid.net/auth/2.0/identifier_select','openid.identity':'http://specs.openid.net/auth/2.0/identifier_select'});return `https://steamcommunity.com/openid/login?${p}`}
async function verifySteam(req){const p=new URLSearchParams();for(const [k,v] of Object.entries(req.query))p.set(k,String(v));p.set('openid.mode','check_authentication');const r=await fetch('https://steamcommunity.com/openid/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p.toString()});const text=await r.text();if(!r.ok||!/is_valid\s*:\s*true/i.test(text))throw new Error('Steam OpenID verification failed');const m=String(req.query.openid_claimed_id||req.query['openid.claimed_id']||'').match(/\/id\/(\d{17})$/);if(!m)throw new Error('SteamID not found');return m[1]}
async function steamProfile(id){if(!STEAM_API_KEY)return {name:`Steam ${id.slice(-6)}`,avatar:''};try{const u=new URL('https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/');u.searchParams.set('key',STEAM_API_KEY);u.searchParams.set('steamids',id);const r=await fetch(u);if(!r.ok)return {name:`Steam ${id.slice(-6)}`,avatar:''};const p=(await r.json())?.response?.players?.[0];return {name:p?.personaname||`Steam ${id.slice(-6)}`,avatar:p?.avatarfull||''}}catch{return {name:`Steam ${id.slice(-6)}`,avatar:''}}}
async function marketPrice(name){if(!name)return null;const key=String(name);const hit=marketCache.get(key);if(hit&&hit.expires>Date.now())return hit.value;try{const u=new URL('https://steamcommunity.com/market/priceoverview/');u.searchParams.set('country','ru');u.searchParams.set('currency','5');u.searchParams.set('appid','730');u.searchParams.set('market_hash_name',key);u.searchParams.set('format','json');const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw new Error('market');const j=await r.json();const raw=j?.lowest_price||j?.median_price||'';const n=Number(String(raw).replace(/[^0-9,\.]/g,'').replace(',','.'));const value=Number.isFinite(n)&&n>0?Math.round(n*100):null;marketCache.set(key,{value,expires:Date.now()+120000});return value}catch{marketCache.set(key,{value:null,expires:Date.now()+30000});return null}}
async function inventory(id){const u=new URL(`https://steamcommunity.com/inventory/${id}/730/2`);u.searchParams.set('l','english');u.searchParams.set('count','2500');const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 (compatible; Keyser/2.0)'}});if(!r.ok)throw new Error(`Steam inventory HTTP ${r.status}`);const j=await r.json();if(j.success!==1)throw new Error('Steam inventory unavailable');const d=new Map((j.descriptions||[]).map(x=>[`${x.classid}_${x.instanceid}`,x]));const raw=(j.assets||[]).map(a=>{const x=d.get(`${a.classid}_${a.instanceid}`);if(!x)return null;const icon=x.icon_url_large||x.icon_url;return {assetid:a.assetid,classid:a.classid,instanceid:a.instanceid,name:x.market_hash_name||x.name,marketName:x.market_hash_name||x.name,icon:icon?`https://community.cloudflare.steamstatic.com/economy/image/${icon}/256fx256f`:'',tradable:!!x.tradable,marketable:!!x.marketable,type:x.type||''}}).filter(Boolean);const limited=raw.slice(0,60);for(let i=0;i<limited.length;i+=5)await Promise.all(limited.slice(i,i+5).map(async x=>{x.priceCents=await marketPrice(x.marketName)}));return raw}
app.get('/auth/steam',(_,res)=>res.redirect(steamLogin()));
app.get('/auth/steam/callback',async(req,res)=>{try{const steamid=await verifySteam(req);const p=await steamProfile(steamid);const t=Date.now();const old=db.prepare('SELECT * FROM users WHERE steamid=?').get(steamid);let id;if(old){db.prepare('UPDATE users SET name=?,avatar=?,updated_at=? WHERE id=?').run(p.name,p.avatar,t,old.id);id=old.id}else{id=db.prepare('INSERT INTO users(steamid,name,avatar,created_at,updated_at) VALUES(?,?,?,?,?)').run(steamid,p.name,p.avatar,t,t).lastInsertRowid}setCookie(res,session(id));res.redirect('/')}catch(e){console.error(e);res.status(502).send('Не удалось подтвердить вход через Steam. Вернитесь на сайт и попробуйте ещё раз.')}});
app.post('/auth/logout',(req,res)=>{clearCookie(res,cookies(req.headers.cookie||'').session);res.json({ok:true})});
app.get('/api/config',(_,res)=>res.json({brand:BRAND_NAME,telegram:TELEGRAM_URL}));
app.get('/api/me',(req,res)=>{const u=user(req);if(!u)return res.json({authenticated:false});res.json({authenticated:true,user:{id:u.id,steamid:u.steamid,name:u.name,avatar:u.avatar,balanceCents:u.balance_cents}})});
app.get('/api/inventory',async(req,res)=>{const u=user(req);if(!u)return res.status(401).json({authenticated:false});try{res.json({authenticated:true,items:await inventory(u.steamid)})}catch(e){console.error(e);res.status(502).json({error:'Steam не вернул инвентарь. Проверьте, что инвентарь профиля открыт.'})}});
app.get('/api/live-drops',(_,res)=>res.json(db.prepare('SELECT id,user_name as userName,item_name as itemName,item_icon as itemIcon,price_cents as priceCents,created_at as createdAt FROM live_drops ORDER BY created_at DESC LIMIT 30').all()));
app.get('/api/events',(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache, no-transform');res.setHeader('Connection','keep-alive');res.flushHeaders?.();clients.add(res);res.write(`event: ready\ndata: ${JSON.stringify({online:clients.size})}\n\n`);req.on('close',()=>clients.delete(res))});
app.get('/api/online',(_,res)=>res.json({online:clients.size}));
app.get('/api/support/messages',(req,res)=>{const u=user(req);if(!u)return res.status(401).json({error:'login_required'});res.json(db.prepare('SELECT id,message,created_at as createdAt FROM support_messages WHERE user_id=? ORDER BY id DESC LIMIT 50').all(u.id).reverse())});
app.post('/api/support/messages',(req,res)=>{const u=user(req);if(!u)return res.status(401).json({error:'login_required'});const m=String(req.body?.message||'').trim();if(!m||m.length>2000)return res.status(400).json({error:'invalid_message'});const r=db.prepare('INSERT INTO support_messages(user_id,message,created_at) VALUES(?,?,?)').run(u.id,m,Date.now());res.json({id:r.lastInsertRowid,message:m,createdAt:Date.now()})});
app.post('/api/upgrade/preview',(req,res)=>{const u=user(req);if(!u)return res.status(401).json({error:'login_required'});const {fromAssetId,toAssetId}=req.body||{};if(!fromAssetId||!toAssetId)return res.status(400).json({error:'Выберите оба предмета'});res.json({ok:true,message:'Колесо проверено сервером. Перед запуском реальной передачи предметов подключите trading backend; клиент не объявляет победу сам.'})});
// Live drops are intentionally not writable from the browser. They must be produced by the trusted game/trade backend.
app.get('/api/cases',(req,res)=>{if(!user(req))return res.json({authenticated:false,cases:[]});res.json({authenticated:true,cases:[]})});
app.listen(PORT,()=>console.log(`${BRAND_NAME}: ${BASE_URL}`));
